service: graphql-api

provider:
  name: aws
  runtime: nodejs6.10

package:
  exclude: 
    - node_modules
    - stories.txt
    - yarn.lock

functions:
  graphql:
    handler: dist/handler.graphql
    events:
      - http:
          path: graphql
          method: post
          cors: true

plugins:
  # - serverless-webpack
  - serverless-offline

custom:
  serverless-offline:
    port: 4000